<?php
define ( "_DEFAULT_DURATION", "N.A. Meetings are 90 minutes long (an hour and a half), unless otherwise indicated." );
define ( "_PDF_AUTHOR", "Greater New York Region of Narcotics Anonymous" );
define ( "_PDF_CHANGE_NOTE", "See the center page for meeting list update form." );
define ( "_PDF_CREATOR", "http://www.newyorkna.org/nameetings/" );
define ( "_PDF_BASIC_HEADER", "Customized Printable Meeting List" );

define ( "_PDF_BKASC_LIST_URL", "Regional Web Site: http://newyorkna.org" );
define ( "_PDF_BKASC_LIST", "Meeting List Produced by the Kings Bay Area Service Committee" );
define ( "_PDF_BKASC_LIST_BANNER", "Narcotics Anonymous Meetings" );
define ( "_PDF_BKASC_LIST_BANNER_2", "In" );
define ( "_PDF_BKASC_LIST_BANNER_3", "Brooklyn" );
define ( "_PDF_BKASC_QR_A", "mobile.newyorkna.org");
define ( "_PDF_BKASC_QR_B", "newyorkna.org");
define ( "_PDF_BKASC_LIST_DUR_INTRO", "Meeting Duration: " );
define ( "_PDF_BKASC_LIST_DUR_15", "15 Min." );
define ( "_PDF_BKASC_LIST_DUR_30", "30 Min." );
define ( "_PDF_BKASC_LIST_DUR_45", "45 Min." );
define ( "_PDF_BKASC_LIST_DUR_60", "1 Hr." );
define ( "_PDF_BKASC_LIST_FORMAT_KEY", "Format Key" );
define ( "_PDF_BKASC_LIST_HEADER_TOWN", "Neighborhood" );
define ( "_PDF_BKASC_LIST_HEADER_NAME", "Name" );
define ( "_PDF_BKASC_LIST_HEADER_LOCATION", "Location" );
define ( "_PDF_BKASC_LIST_HEADER_TIME", "Start Time" );
define ( "_PDF_BKASC_LIST_HEADER_FORMAT", "Format" );
define ( "_PDF_BKASC_LIST_HELPLINE_REGION", "Regional Helpline: (212) 929-NANA (6262)" );
define ( "_PDF_BKASC_LIST_MAILING", "Mailing Address:" );
define ( "_PDF_BKASC_LIST_NAME", "Name" );
define ( "_PDF_BKASC_LIST_PHONE", "Phone #" );
define ( "_PDF_BKASC_LIST_SUBCOMMITTEES", "Kings Bay Area Service Committee Meetings" );
define ( "_PDF_BKASC_NAME_TEXT", "" );

define ( "_PDF_BKASC_LIST_SAYING_1", "SUGGESTIONS FOR STAYING CLEAN" );
define ( "_PDF_BKASC_LIST_SAYING_2", "Don't use, no matter what" );
define ( "_PDF_BKASC_LIST_SAYING_3", "Avoid People, places and things you used with or at" );
define ( "_PDF_BKASC_LIST_SAYING_4", "Come early and stay late" );
define ( "_PDF_BKASC_LIST_SAYING_5", "Go to 90 meetings in 90 days" );
define ( "_PDF_BKASC_LIST_SAYING_6", "Get and use a sponsor" );
define ( "_PDF_BKASC_LIST_SAYING_7", "Use the phone" );
define ( "_PDF_BKASC_LIST_SAYING_8", "Get Involved" );
define ( "_PDF_BKASC_LIST_SAYING_9", "Keep coming back, it Works!" );

define ( "_PDF_BROOKLYN_LIST_URL", "Area Web Site: http://bklynna.org/" );
define ( "_PDF_BROOKLYN_LIST", "Meeting List Produced by the Brooklyn Area Service Committee" );
define ( "_PDF_BROOKLYN_LIST_BANNER", "Narcotics Anonymous Meetings" );
define ( "_PDF_BROOKLYN_LIST_BANNER_2", "In" );
define ( "_PDF_BROOKLYN_LIST_BANNER_3", "Brooklyn Area" );
define ( "_PDF_BROOKLYN_QR_A", "bklynna.org");
define ( "_PDF_BROOKLYN_QR_B", "newyorkna.org");
define ( "_PDF_BROOKLYN_LIST_DUR_INTRO", "Meeting Duration: " );
define ( "_PDF_BROOKLYN_LIST_DUR_15", "15 Min." );
define ( "_PDF_BROOKLYN_LIST_DUR_30", "30 Min." );
define ( "_PDF_BROOKLYN_LIST_DUR_45", "45 Min." );
define ( "_PDF_BROOKLYN_LIST_DUR_60", "1 Hr." );
define ( "_PDF_BROOKLYN_LIST_FORMAT_KEY", "Format Key" );
define ( "_PDF_BROOKLYN_LIST_HEADER_TOWN", "Neighborhood" );
define ( "_PDF_BROOKLYN_LIST_HEADER_NAME", "Name" );
define ( "_PDF_BROOKLYN_LIST_HEADER_LOCATION", "Location" );
define ( "_PDF_BROOKLYN_LIST_HEADER_TIME", "Start Time" );
define ( "_PDF_BROOKLYN_LIST_HEADER_FORMAT", "Format" );
define ( "_PDF_BROOKLYN_LIST_HELPLINE_REGION", "Regional Helpline: (212) 929-NANA (6262)" );
define ( "_PDF_BROOKLYN_LIST_MAILING", "Mailing Address:" );
define ( "_PDF_BROOKLYN_LIST_NAME", "Name" );
define ( "_PDF_BROOKLYN_LIST_PHONE", "Phone #" );
define ( "_PDF_BROOKLYN_LIST_SUBCOMMITTEES", "Brooklyn Area Service Committee Meetings" );
define ( "_PDF_BROOKLYN_NAME_TEXT", "" );

define ( "_PDF_BROOKLYN_LIST_SAYING_1", "SUGGESTIONS FOR STAYING CLEAN" );
define ( "_PDF_BROOKLYN_LIST_SAYING_2", "Don't use, no matter what" );
define ( "_PDF_BROOKLYN_LIST_SAYING_3", "Avoid People, places and things you used with or at" );
define ( "_PDF_BROOKLYN_LIST_SAYING_4", "Come early and stay late" );
define ( "_PDF_BROOKLYN_LIST_SAYING_5", "Go to 90 meetings in 90 days" );
define ( "_PDF_BROOKLYN_LIST_SAYING_6", "Get and use a sponsor" );
define ( "_PDF_BROOKLYN_LIST_SAYING_7", "Use the phone" );
define ( "_PDF_BROOKLYN_LIST_SAYING_8", "Get Involved" );
define ( "_PDF_BROOKLYN_LIST_SAYING_9", "Keep coming back, it Works!" );

define ( "_PDF_WQASC_LIST", "Meeting List Produced by the Western Queens Area Service Committee" );
define ( "_PDF_WQASC_LIST_BANNER", "Narcotics Anonymous Meetings" );
define ( "_PDF_WQASC_LIST_BANNER_2", "In" );
define ( "_PDF_WQASC_LIST_BANNER_3", "Queens" );
define ( "_PDF_WQASC_LIST_DUR_INTRO", "Meeting Duration: " );
define ( "_PDF_WQASC_LIST_DUR_15", "15 Min." );
define ( "_PDF_WQASC_LIST_DUR_30", "30 Min." );
define ( "_PDF_WQASC_LIST_DUR_45", "45 Min." );
define ( "_PDF_WQASC_LIST_DUR_60", "1 Hr." );
define ( "_PDF_WQASC_LIST_FORMAT_KEY", "Format Key" );
define ( "_PDF_WQASC_LIST_HEADER_TOWN", "Neighborhood" );
define ( "_PDF_WQASC_LIST_HEADER_NAME", "Name" );
define ( "_PDF_WQASC_LIST_HEADER_LOCATION", "Location" );
define ( "_PDF_WQASC_LIST_HEADER_TIME", "Start Time" );
define ( "_PDF_WQASC_LIST_HEADER_FORMAT", "Format" );
define ( "_PDF_WQASC_LIST_NAME", "Name" );
define ( "_PDF_WQASC_LIST_PHONE", "Phone #" );
define ( "_PDF_WQASC_LIST_URL", "Web Site: http://westernqueensna.org/" );
define ( "_PDF_WQASC_LIST_HELPLINE", "Helpline: (718) 962-6244" );

define ( "_PDF_CONTD", " (Continued)" );
define ( "_PDF_DISCLAIMER", "This meeting list is printed quarterly, and is subject to change without notice.\nThe Web site is usually more up to date than the list." );
define ( "_PDF_DOC_NAME", "Custom_Meeting_List" );
define ( "_PDF_DOC_NAME_PDA", "Custom_Meeting_List_PDA" );
define ( "_PDF_FILE_TITLE", "Selecting This will Download this Page As a Printable Adobe Acrobat PDF File." );
define ( "_PDF_FILE", "Download As a Printable Adobe Acrobat PDF File." );
define ( "_PDF_LEGEND_HEADER", "Meeting Format Codes" );
define ( "_PDF_MAIN_HEADER", "GNY Printable Meeting List Section 2" );
define ( "_PDF_NOTE_PROMPT", "Enter a note to be displayed on the PDF cover page:" );

define ( "_PDF_NYC_LIST_URL", "NYCASC Web Site: http://nycna.org" );
define ( "_PDF_NYC_LIST", "Meeting List Co-Produced by the New York City and the Manhattan Area Service Committees" );
define ( "_PDF_NYC_LIST_BANNER", "Narcotics Anonymous Meetings" );
define ( "_PDF_NYC_LIST_BANNER_2", "In" );
define ( "_PDF_NYC_LIST_BANNER_3", "Manhattan" );
define ( "_PDF_NYC_LIST_CORRECTIONS1", "NYCASC Mailing Address:" );
define ( "_PDF_NYC_LIST_CORRECTIONS2", "PMB # 329" );
define ( "_PDF_NYC_LIST_CORRECTIONS3", "70-A Greenwich Ave." );
define ( "_PDF_NYC_LIST_CORRECTIONS4", "New York, NY 10011" );
define ( "_PDF_NYC_LIST_CORRECTIONS5", "email: meetinglist@nycna.org" );
define ( "_PDF_NYC_LIST_CORRECTIONS1A", "MASC Mailing Address:" );
define ( "_PDF_NYC_LIST_CORRECTIONS2A", "P.O Box 8391" );
define ( "_PDF_NYC_LIST_CORRECTIONS3A", "JAF Station" );
define ( "_PDF_NYC_LIST_CORRECTIONS4A", "New York, NY 10001" );
define ( "_PDF_NYC_QR_A", "nycna.org");
define ( "_PDF_NYC_QR_B", "newyorkna.org");
define ( "_PDF_NYC_LIST_DUR_INTRO", "Meeting Duration: " );
define ( "_PDF_NYC_LIST_DUR_15", "15 Min." );
define ( "_PDF_NYC_LIST_DUR_30", "30 Min." );
define ( "_PDF_NYC_LIST_DUR_45", "45 Min." );
define ( "_PDF_NYC_LIST_DUR_60", "1 Hr." );
define ( "_PDF_NYC_LIST_FORMAT_KEY", "Format Key" );
define ( "_PDF_NYC_LIST_HEADER_TOWN", "Neighborhood" );
define ( "_PDF_NYC_LIST_HEADER_NAME", "Name" );
define ( "_PDF_NYC_LIST_HEADER_LOCATION", "Location" );
define ( "_PDF_NYC_LIST_HEADER_TIME", "Start Time" );
define ( "_PDF_NYC_LIST_HEADER_FORMAT", "Format" );
define ( "_PDF_NYC_LIST_HELPLINE_REGION", "Regional Helpline: (212) 929-NANA (6262)" );
define ( "_PDF_NYC_LIST_MAILING", "Mailing Address:" );
define ( "_PDF_NYC_LIST_NAME", "Name" );
define ( "_PDF_NYC_LIST_PHONE", "Phone #" );
define ( "_PDF_NYC_LIST_EMAIL", "meetinglist@nycna.org" );
define ( "_PDF_NYC_LIST_SUBCOMMITTEE1", "NYCASC Meeting Info:" );
define ( "_PDF_NYC_LIST_SUBCOMMITTEE2", "2:00 PM, third Sunday of every month" );
define ( "_PDF_NYC_LIST_SUBCOMMITTEE3", "Greater New York Regional RSO" );
define ( "_PDF_NYC_LIST_SUBCOMMITTEE4", "154 Christopher Street, Suite 1A" );
define ( "_PDF_NYC_LIST_SUBCOMMITTEE5", "(Between Washington & Greenwich)" );
define ( "_PDF_NYC_LIST_SUBCOMMITTEE6", "Manhattan, NY 10014" );
define ( "_PDF_NYC_LIST_SUBCOMMITTEE7", "12:30PM for Steering Committee" );
define ( "_PDF_NYC_LIST_SUBCOMMITTEE1A", "MASC Meeting Info:" );
define ( "_PDF_NYC_LIST_SUBCOMMITTEE2A", "10:00 AM, first Saturday of every month" );
define ( "_PDF_NYC_LIST_SUBCOMMITTEE3A", "EM Moore Houses" );
define ( "_PDF_NYC_LIST_SUBCOMMITTEE4A", "(Basement)" );
define ( "_PDF_NYC_LIST_SUBCOMMITTEE5A", "160 W 116th St" );
define ( "_PDF_NYC_LIST_SUBCOMMITTEE6A", "Manhattan, NY 10026" );
define ( "_PDF_NYC_LIST_SUBCOMMITTEE6B", "" );

define ( "_PDF_SSA_LIST_URL", "Web Site: http://nanewyork.org" );
define ( "_PDF_SSA_LIST", "Meeting List Produced by the Simply Spiritual Area Service Committee" );
define ( "_PDF_SSA_LIST_BANNER", "Narcotics Anonymous Meetings" );
define ( "_PDF_SSA_LIST_BANNER_2", "On" );
define ( "_PDF_SSA_LIST_BANNER_3", "Long Island" );
define ( "_PDF_SSA_LIST_BANNER_4", '"Our Message is hope and the promise of freedom from active addiction."' );
define ( "_PDF_SSA_LIST_BANNER_5", '"An addict, any addict, can stop using drugs, lose the desire to use, and find a new way to live."' );
define ( "_PDF_SSA_LIST_CORRECTIONS1", "SSASC Mailing Address:" );
define ( "_PDF_SSA_LIST_CORRECTIONS2", "P.O. Box 658, Amityville, NY 11701" );
define ( "_PDF_SSA_LIST_DUR_INTRO", "Meeting Duration: " );
define ( "_PDF_SSA_LIST_DUR_15", "15 Min." );
define ( "_PDF_SSA_LIST_DUR_30", "30 Min." );
define ( "_PDF_SSA_LIST_DUR_45", "45 Min." );
define ( "_PDF_SSA_LIST_DUR_60", "1 Hr." );
define ( "_PDF_SSA_LIST_FORMAT_KEY", "Format Key" );
define ( "_PDF_SSA_LIST_HEADER_TOWN", "Neighborhood" );
define ( "_PDF_SSA_LIST_HEADER_NAME", "Name" );
define ( "_PDF_SSA_LIST_HEADER_LOCATION", "Location" );
define ( "_PDF_SSA_LIST_HEADER_TIME", "Start Time" );
define ( "_PDF_SSA_LIST_HEADER_FORMAT", "Format" );
define ( "_PDF_SSA_LIST_HELPLINE", "Helpline: (631) 689-NANA (6262)" );
define ( "_PDF_SSA_LIST_NAME", "Name" );
define ( "_PDF_SSA_LIST_PHONE", "Phone #" );
define ( "_PDF_SSA_LIST_EMAIL", "meetinglist@nycna.org" );
define ( "_PDF_SSA_LIST_SUBCOMMITTEES", "Service Committee Meetings" );
define ( "_PDF_SSA_LIST_TIME_NOTE", "NA Meetings are 90 Minutes (An Hour and A Half), Unless Otherwise Noted." );
define ( "_PDF_SSA_LIST_HELPLINES", "Helplines:" );
define ( "_PDF_SSA_LIST_HELPLINE_SUFFOLK", "Suffolk County: (631) 689-NANA (6262)" );
define ( "_PDF_SSA_LIST_HELPLINE_NASSAU", "Nassau County: (516) 827-9500" );
define ( "_PDF_SSA_LIST_HELPLINE_REGION", "Regional: (212) 929-NANA (6262)" );
define ( "_PDF_SSA_LIST_DISCLAIMER", "This list is printed quarterly, and subject to change without notice.\nThe Web site is usually more up to date than the printed list." );

define ( "_PDF_SAS_LIST_URL", "SASNA Web Site: longislandna.com" );
define ( "_PDF_SAS_LIST", "Meeting List Produced by the Suffolk Area Service Committee" );
define ( "_PDF_SAS_LIST_BANNER", "Narcotics Anonymous Meetings" );
define ( "_PDF_SAS_LIST_BANNER_2", "On" );
define ( "_PDF_SAS_LIST_BANNER_3", "Long Island" );
define ( "_PDF_SAS_LIST_CORRECTIONS1", "SASASC Mailing Address:" );
define ( "_PDF_SAS_LIST_CORRECTIONS2", "P.O. Box 460, Islip Terrace, NY 11752" );
define ( "_PDF_SAS_QR_A", "sasna.org");
define ( "_PDF_SAS_QR_B", "mobile.sasna.org");
define ( "_PDF_SAS_LIST_DUR_INTRO", "Meeting Duration: " );
define ( "_PDF_SAS_LIST_DUR_15", "15 Min." );
define ( "_PDF_SAS_LIST_DUR_30", "30 Min." );
define ( "_PDF_SAS_LIST_DUR_45", "45 Min." );
define ( "_PDF_SAS_LIST_DUR_60", "1 Hr." );
define ( "_PDF_SAS_LIST_FORMAT_KEY", "Format Key" );
define ( "_PDF_SAS_LIST_HEADER_TOWN", "Neighborhood" );
define ( "_PDF_SAS_LIST_HEADER_NAME", "Name" );
define ( "_PDF_SAS_LIST_HEADER_LOCATION", "Location" );
define ( "_PDF_SAS_LIST_HEADER_TIME", "Start Time" );
define ( "_PDF_SAS_LIST_HEADER_FORMAT", "Format" );
define ( "_PDF_SAS_LIST_HELPLINE", "Helpline: (631) 689-NANA (6262)" );
define ( "_PDF_SAS_LIST_NAME", "Name" );
define ( "_PDF_SAS_LIST_PHONE", "Phone #" );
define ( "_PDF_SAS_LIST_EMAIL", "meetinglist@nycna.org" );
define ( "_PDF_SAS_LIST_SUBCOMMITTEES", "Suffolk Area Service Committee Meetings" );
define ( "_PDF_SAS_LIST_TIME_NOTE", "NA Meetings are 90 Minutes (An Hour and A Half), Unless Otherwise Noted." );
define ( "_PDF_SAS_LIST_HELPLINES", "Helplines:" );
define ( "_PDF_SAS_LIST_HELPLINE_SUFFOLK", "Suffolk County: (631) 689-NANA (6262)" );
define ( "_PDF_SAS_LIST_YAP_1", "Text your zip code to" );
define ( "_PDF_SAS_LIST_YAP_2", "(631) 237-9JFT (9538)" );
define ( "_PDF_SAS_LIST_YAP_3", "to find a meeting" );
define ( "_PDF_SAS_LIST_HELPLINE_NASSAU", "Nassau County and Regional: (516) 827-9500" );
define ( "_PDF_SAS_LIST_HELPLINE_REGION", "Regional Web Site: nanewyork.org" );
define ( "_PDF_SAS_LIST_DISCLAIMER", "This list is printed quarterly, and subject to change without notice.\nThe Web site is usually more up to date than the printed list." );

define ( "_PDF_OAAS_LIST_URL", "Web Site: http://openarmsarea.com" );
define ( "_PDF_OAAS_LIST", "Meeting List Produced by the Open Arms Area Service Committee" );
define ( "_PDF_OAAS_LIST_BANNER", "Narcotics Anonymous Meetings" );
define ( "_PDF_OAAS_LIST_BANNER_2", "In the" );
define ( "_PDF_OAAS_LIST_BANNER_3", "Hudson Valley of New York" );
define ( "_PDF_OAAS_LIST_CORRECTIONS1", "OAASC Mailing Address:" );
define ( "_PDF_OAAS_LIST_CORRECTIONS2", "?" );
define ( "_PDF_OAAS_LIST_DUR_INTRO", "Meeting Duration: " );
define ( "_PDF_OAAS_LIST_DUR_15", "15 Min." );
define ( "_PDF_OAAS_LIST_DUR_30", "30 Min." );
define ( "_PDF_OAAS_LIST_DUR_45", "45 Min." );
define ( "_PDF_OAAS_LIST_DUR_60", "1 Hr." );
define ( "_PDF_OAAS_LIST_FORMAT_KEY", "Format Key" );
define ( "_PDF_OAAS_LIST_HEADER_TOWN", "Neighborhood" );
define ( "_PDF_OAAS_LIST_HEADER_NAME", "Name" );
define ( "_PDF_OAAS_LIST_HEADER_LOCATION", "Location" );
define ( "_PDF_OAAS_LIST_HEADER_TIME", "Start Time" );
define ( "_PDF_OAAS_LIST_HEADER_FORMAT", "Format" );
define ( "_PDF_OAAS_LIST_HELPLINE", "Helpline: (845) 431-6996" );
define ( "_PDF_OAAS_LIST_NAME", "Name" );
define ( "_PDF_OAAS_LIST_PHONE", "Phone #" );
define ( "_PDF_OAAS_LIST_EMAIL", "meetinglist@openarmsarea.com" );
define ( "_PDF_OAAS_LIST_SUBCOMMITTEES", "Open Arms Area Service Committee Meetings" );
define ( "_PDF_OAAS_LIST_TIME_NOTE", "NA Meetings are 90 Minutes (An Hour and A Half), Unless Otherwise Noted." );
define ( "_PDF_OAAS_LIST_HELPLINES", "Helplines:" );
define ( "_PDF_OAAS_LIST_HELPLINE_OAASC", "Hudson Valley: (845) 431-6996" );
define ( "_PDF_OAAS_LIST_HELPLINE_REGION", "Regional: (212) 929-NANA (6262)" );
define ( "_PDF_OAAS_LIST_DISCLAIMER", "This list is printed quarterly, and subject to change without notice.\nThe Web site is usually more up to date than the printed list." );

define ( "_PDF_PAGE", "Page" );
define ( "_PDF_PALM_TITLE", "Selecting This will Download this Page as a PDF File Optimized for PDA Display." );
define ( "_PDF_PALM", "Download As a PDF file optimized for PDA display." );
define ( "_PDF_PRINTED_ON", "Printed on " );

define ( "_PDF_SASNA_LIST", "Main SASNA Meeting List" );
define ( "_PDF_SASNA_LIST_A", "sasna.org" );
define ( "_PDF_SASNA_LIST_B", "mobile.sasna.org" );
define ( "_PDF_SASNA_LIST_BANNER", "Narcotics Anonymous Meetings" );
define ( "_PDF_SASNA_LIST_BANNER_2", "On" );
define ( "_PDF_SASNA_LIST_BANNER_3", "Long Island, New York" );
define ( "_PDF_SASNA_LIST_BANNER_4", "Eastern Long Island Area Service" );
define ( "_PDF_SASNA_LIST_CORRECTIONS", "If you have changes or corrections to the meeting list, you can use the Online (Web site) meeting list correction form at:" );
define ( "_PDF_SASNA_LIST_DUR_INTRO", "Meeting Duration: " );
define ( "_PDF_SASNA_LIST_DUR_15", "15 Min." );
define ( "_PDF_SASNA_LIST_DUR_30", "30 Min." );
define ( "_PDF_SASNA_LIST_DUR_45", "45 Min." );
define ( "_PDF_SASNA_LIST_DUR_60", "1 Hr." );
define ( "_PDF_SASNA_LIST_ELI", "Eastern Long Island Area" );
define ( "_PDF_SASNA_LIST_FORMAT_KEY", "Format Key" );
define ( "_PDF_SASNA_LIST_GSR_NOTE", "You can also have your GSR bring corrections to the next Area Service Meeting.\nAll change requests MUST be verifiable!" );
define ( "_PDF_SASNA_LIST_HEADER_TOWN", "Town" );
define ( "_PDF_SASNA_LIST_HEADER_NAME", "Name" );
define ( "_PDF_SASNA_LIST_HEADER_LOCATION", "Location" );
define ( "_PDF_SASNA_LIST_HEADER_TIME", "Start Time" );
define ( "_PDF_SASNA_LIST_HEADER_FORMAT", "Format" );
define ( "_PDF_SASNA_LIST_HELPLINES", "Helplines:" );
define ( "_PDF_SASNA_LIST_HELPLINE_SUFFOLK", "Suffolk County: (631) 689-NANA (6262)" );
define ( "_PDF_SASNA_LIST_HELPLINE_ELI", "Suffolk County: (631) 884-9500" );
define ( "_PDF_SASNA_LIST_HELPLINE_NASSAU", "Nassau County: (516) 827-9500" );
define ( "_PDF_SASNA_LIST_HELPLINE_QUEENS", "Queens Area: (718) 962-6244" );
define ( "_PDF_SASNA_LIST_HELPLINE_REGION", "Regional: (212) 929-NANA (6262)" );
define ( "_PDF_SASNA_LIST_MAINTAIN", "This meeting list is maintained by the Suffolk Area Service Committee of Narcotics Anonymous. The original source for this meeting list is the Online (Web site) list at:" );
define ( "_PDF_SASNA_LIST_MAILING", "Mailing Address:" );
define ( "_PDF_SASNA_LIST_MAILING_ELI", "Send All Written Correspondence to:" );
define ( "_PDF_SASNA_LIST_PO", "PO Box 460" );
define ( "_PDF_SASNA_LIST_PO_ELI", "PO Box 245" );
define ( "_PDF_SASNA_LIST_SASNA", "SASNA" );
define ( "_PDF_SASNA_LIST_SUBCOMMITTEES", "Suffolk Area Service Committee Meetings" );
define ( "_PDF_SASNA_LIST_ELI_SUBCOMMITTEES", "Eastern Long Island Area Service Committee Meetings" );
define ( "_PDF_SASNA_LIST_TOWN", "Islip Terrace, NY 11752" );
define ( "_PDF_SASNA_LIST_TOWN_ELI", "Jamesport, NY 11947" );
define ( "_PDF_SASNA_LIST_TRADS", "In keeping with our 1st and 3rd Traditions, ALL ADDICTS are welcome to attend ANY Narcotics Anonymous meeting." );
define ( "_PDF_SASNA_LIST_ELI_TRADS", "All addicts are welcome at any Narcotics Anonymous meeting." );
define ( "_PDF_SASNA_LIST_URL", "Web Site: http://www.sasna.org/" );
define ( "_PDF_SASNA_LIST_URL_GENERIC", "Web Site: http://www.longislandna.org/" );
define ( "_PDF_SASNA_LIST_URL_CORRECTIONS", "http://www.sasna.org/changes" );
define ( "_PDF_SASNA_LIST_URL_MEETINGS", "http://www.sasna.org/meetings" );
define ( "_PDF_SASNA_LIST_WELCOME", "Welcome:" );
define ( "_PDF_SASNA_LIST_WHATIS_HEADER", "What is the Narcotics Anonymous program?" );
define ( "_PDF_SASNA_LIST_WHATIS_TEXT", "NA is a nonprofit fellowship or society of men and women for whom drugs had become a major problem. We are recovering addicts who meet regularly to help each other stay clean. This is a program of complete abstinence from all drugs. There is only one requirement for membership, the desire to stop using. We suggest that you keep an open mind and give yourself a break. Our program is a set of principles written so simply that we can follow them in our daily lives. The most important thing about them is that they work." );
define ( "_PDF_SASNA_LIST_WDR_HEADER", "We Do Recover" );
define ( "_PDF_SASNA_LIST_WDR_TEXT", "When at the end of the road we find that we can no longer function as a human being, either with or without drugs, we all face the same dilemma. What is there left to do? There seems to be this alternative: either go on as best we can to the bitter ends -jails, institutions or death- or find a new way to live. In years gone by, very few addicts ever had this last choice. Those who are addicted today are more fortunate. For the first time in man's entire history, a simple way has been proving itself in the lives of many addicts. It is available to us all. This is a simple spiritual -not religious- program, known as Narcotics Anonymous." );
define ( "_PDF_SASNA_LIST_GENERIC_SUB_1", "Welcome:" );
define ( "_PDF_SASNA_LIST_STEPS_HEADER", "The Twelve Steps" );
define ( "_PDF_SASNA_LIST_TRAD_HEADER", "The Twelve Traditions" );

define ( "_PDF_ABCD_LIST_FORMAT_KEY", "Format Key" );
define ( "_PDF_ABCD_LIST_MAIN_TITLE_TOP", "ABCD Region" );
define ( "_PDF_ABCD_LIST_MAIN_TITLE_MIDDLE", "of" );
define ( "_PDF_ABCD_LIST_MAIN_TITLE_BOTTOM", "Narcotics Anonymous" );
define ( "_PDF_ABCD_LIST_SUB_TITLE", "NA Meeting List" );
define ( "_PDF_ABCD_LIST_DATE_FORMAT", '\R\e\v\i\s\e\d F, Y' );
define ( "_PDF_ABCD_LIST_NAME", "Name" );
define ( "_PDF_ABCD_LIST_PHONE", "Phone #" );
define ( "_PDF_ABCD_LIST_SUBCOMMITTEE_HEADING", "Service Meetings" );
define ( "_PDF_ABCD_LIST_HELPLINE", "Regional Helpline: (888) 399-5519" );
define ( "_PDF_ABCD_LIST_WEBSITE", "Web Site: http://abcdrna.org" );
define ( "_PDF_ABCD_LIST_DISCLAIMER_LINE_1", "The information in this book was as accurate as possible at the time of printing." );
define ( "_PDF_ABCD_LIST_DISCLAIMER_LINE_2", "Occasionally, groups may move or change their time." );
define ( "_PDF_ABCD_LIST_DISCLAIMER_LINE_3", "If you go to a listed meeting and it is not there, please go to another meeting." );
define ( "_PDF_ABCD_LIST_WHO_HEADING", "Who Is An Addict?" );
define ( "_PDF_ABCD_LIST_WHAT_HEADING", "What Is the Narcotics Anonymous Program?" );
define ( "_PDF_ABCD_LIST_WHY_HEADING", "Why Are We Here?" );
define ( "_PDF_ABCD_LIST_WE_HEADING", "We Do Recover" );

define ( "_PDF_NASC_LIST_FORMAT_KEY", "Format Key" );
define ( "_PDF_NASC_LIST_MAIN_TITLE_TOP", "Nassau Area" );
define ( "_PDF_NASC_LIST_MAIN_TITLE_MIDDLE", "of" );
define ( "_PDF_NASC_LIST_MAIN_TITLE_BOTTOM", "Narcotics Anonymous" );
define ( "_PDF_NASC_LIST_SUB_TITLE", "NA Meeting List" );
define ( "_PDF_NASC_LIST_DATE_FORMAT", '\R\e\v\i\s\e\d F, Y' );
define ( "_PDF_NASC_LIST_NAME", "Name" );
define ( "_PDF_NASC_LIST_PHONE", "Phone #" );
define ( "_PDF_NASC_LIST_SUBCOMMITTEE_HEADING", "Service Meetings" );
define ( "_PDF_NASC_LIST_HELPLINE", "Helpline: (516) 827-9500" );
define ( "_PDF_NASC_LIST_WEBSITE", "Web Site: http://nassauna.org" );
define ( "_PDF_NASC_LIST_DISCLAIMER_LINE_1", "The information in this list was as accurate as possible at the time of printing." );
define ( "_PDF_NASC_LIST_DISCLAIMER_LINE_2", "Occasionally, groups may move or change their time. Meetings are 1hr 30min normally." );
define ( "_PDF_NASC_LIST_DISCLAIMER_LINE_3", "If you go to a listed meeting and it is not there, please go to another meeting." );
define ( "_PDF_NASC_LIST_QR_LABEL_NAWS", "World Services App" );
define ( "_PDF_NASC_LIST_QR_LABEL_BMLT", "iPhone-Only App" );

define ( "_PDF_ELI_ASC_LIST_FORMAT_KEY", "Format Key" );
define ( "_PDF_ELI_ASC_LIST_MAIN_TITLE_TOP", "Eastern Long Island Area" );
define ( "_PDF_ELI_ASC_LIST_MAIN_TITLE_MIDDLE", "of" );
define ( "_PDF_ELI_ASC_LIST_MAIN_TITLE_BOTTOM", "Narcotics Anonymous" );
define ( "_PDF_ELI_ASC_LIST_SUB_TITLE", "NA Meeting List" );
define ( "_PDF_ELI_ASC_LIST_DATE_FORMAT", '\R\e\v\i\s\e\d F, Y' );
define ( "_PDF_ELI_ASC_LIST_NAME", "Name" );
define ( "_PDF_ELI_ASC_LIST_PHONE", "Phone #" );
define ( "_PDF_ELI_ASC_LIST_SUBCOMMITTEE_HEADING", "Service Meetings" );
define ( "_PDF_ELI_ASC_LIST_HELPLINE", "Helpline: (631) 689-NANA (6262)" );
define ( "_PDF_ELI_ASC_LIST_DISCLAIMER_LINE_1", "The information in this list was as accurate as possible at the time of printing." );
define ( "_PDF_ELI_ASC_LIST_DISCLAIMER_LINE_2", "Occasionally, groups may move or change their time." );
define ( "_PDF_ELI_ASC_LIST_DISCLAIMER_LINE_3", "If you go to a listed meeting and it is not there, please go to another meeting." );
define ( "_PDF_ELI_ASC_LIST_STEPS_HEADER", "The Twelve Steps" );
define ( "_PDF_ELI_ASC_LIST_TRAD_HEADER", "The Twelve Traditions" );
define ( "_PDF_ELI_ASC_LIST_URL", "Web Site: http://easternlina.org" );

define ( "_PDF_SOURCE", "This meeting list was printed from the Greater New York Region of Narcotics Anonymous Web Site (http://www.newyorkna.org/nameetings)." );
define ( "_PDF_SPANISH", " - Spanish" );
?>